### ISSUE TITLE
Websocket Example will not connect to Wifi

### ISSUE THREAD

**Issue by gshafer** [akshar001/chhavi#5]
If I change your code from:
 
WiFi.softAP("Chhavi_VEGG","touchDetect");
  wifiMulti.addAP("VEGG_5", "sss3kk2aaaa4");
  while(wifiMulti.run() != WL_CONNECTED) {
        Serial.println("WiFi not connected!");
        delay(1000);
  }
 
 
To:
 
WiFi.softAP("Chhavi_VEGG","touchDetect");
  wifiMulti.addAP("VEGG_5", "sss3kk2aaaa4");
  wifiMulti.addAP(ssid, password);
  while(wifiMulti.run() != WL_CONNECTED) {
        Serial.println("WiFi not connected!");
        delay(1000);
  }
 
I can get wifi to connect.
 
Output from Serial Monitor:
 
rst:0x1 (POWERON_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 188777542, SPIWP:0xee
clk_drv:0x192.168.0.155

**Comment by akshar001** [comment]
Yes, I think we have hard coded it, I will fix it. in repo and update it, thanks for the help anyway.

**Comment by akshar001** [comment]
@gshafer it has been fixed and updated in main branch
